[package]
name = "ironpilot-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ironpilot-application = { version = "0.1.0", path = "../ironpilot-application" }
noyalib = { version = "0.0.16", default-features = false, features = ["minimal"] }

[lints]
workspace = true
